version: '3.8'
services:
  postgres:
    image: postgres
    restart: always 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
   
    
    

  app:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "44044:44044"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - CONFIG_PATH=./config/config.yaml

    
  pgadmin:
    image: dpage/pgadmin4:6.12
    ports:
      - "5080:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./db-data/pgadmin/:/home/rundeck/server/data